# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 477c539c82d33b2d67f38f390a36b3cef34776b7eaa6ddce6b917a5a0024aec409e00dbc3f65386ad4e091887997b30561106d7e588d05b96847804425f01baa

test:
  secret_key_base: 50f0e7d7e1b7963a72a0148b4cbfefeda498f8fc013a4d0b7f91d54dda0f7aaa66d72df58d74d89b45a34cd96cde065c4c273cf8eeba7f882a72dff5520d3541

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
